version: '3.9'
services:
  backend:
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql